[build]
  publish = "public"

[functions."internal-reset-data"]
schedule = "@hourly"

[[redirects]]
  from = "/"
  to = "/v1"
  force = true

[[redirects]]
  from = "/v1/users"
  to = "/.netlify/functions/v1-users"
  status = 200

[[redirects]]
  from = "/v1/login"
  to = "/.netlify/functions/v1-login"
  status = 200

[[redirects]]
  from = "/v1/users/me"
  to = "/.netlify/functions/v1-users-me"
  status = 200

[[redirects]]
  from = "/v1/talks"
  to = "/.netlify/functions/v1-talks"
  status = 200

[[redirects]]
  from = "/v1/talks/likes"
  to = "/.netlify/functions/v1-likes"
  status = 200

[[redirects]]
  from = "/v1/talks/*"
  to = "/.netlify/functions/v1-talks-detail"
  status = 200